version: '3.7'

services:
  radium-demo-db:
    container_name: testdb
    build:
      context: ./db-init
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5433:5433"
    expose:
      - 5433
    environment:
      - POSTGRES_USER=${RADIUM_DB_TEST_USER}
      - POSTGRES_PASSWORD=${RADIUM_DB_DB_PASSWORD}
      - POSTGRES_DB=${RADIUM_DB_TEST}
      - PGPORT=5433
#    volumes:
#      - ./{volumes_dir}}:/var/lib/postgresql/data
    command: -p ${PGPORT}
#    networks:
#      dev-net:
#        aliases:
#          - 'test-db'
#volumes:
#  volumes_dir:
#networks:
#  dev-net:
#    driver: bridge
